config/routes.rb
Storytellingapp::Application.routes.draw do

  resources :stories
  root :to => 'stories#index'

end

app/models/beat.rb
class Beat < ActiveRecord::Base
  
  belongs_to :story  

  attr_accessible :picture, :story_id

  has_attached_file :picture, 
  					:styles => { 
  						:medium => "300x300>", 
  						:thumb => "100x100>" 
  					}

end

app/models/story.rb
class Story < ActiveRecord::Base

  has_many :beats

  attr_accessible :body, :title, :beats_attributes

  validates :title, :presence => true
  validates :body, :presence => true

  accepts_nested_attributes_for :beats

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

	def index
		@stories = Story.all(:order => "created_at desc")
	end

	def new
		@story = Story.new
		3.times { @story.beats.build }
	end

	def create

		@story = Story.new(params[:story])

		if @story.valid? and @story.save
			redirect_to stories_path
		else
			render :action => :new
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Storytellingapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="navbar">
	  <div class="navbar-inner">
	    <a class="brand" href="/stories">Storytelling App</a>
	    <ul class="nav">
	      <li class=""><a href="/stories">Home</a></li>
	      <li class=""><a href="/stories/new">Write your own</a></li>
	    </ul>
	  </div>
	</div>


	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/stories/index.html.erb
<h1>The stories of our lives</h1>

<%= link_to "Write new story", new_story_path, :class => "btn btn-large btn-primary" %>

<hr/>
<% for story in @stories %>
	<div class="story">
		<br/>
		<h2><%= story.title %></h2>
		<br/>
		<br/>
		<% for beat in story.beats %>
			<%= image_tag beat.picture.url(:medium) %>
		<% end %>
		<br/>
		<br/>
		<p><%= story.body %></p>
		<br/>

	</div>
<% end %>

app/views/stories/new.html.erb
<h1>Write a new story</h1>

<%= form_for @story do |f| %>

 	<% @story.errors.full_messages.each do |msg| %>
      <p class="error"><%= msg %></p>
    <% end %>

	<p>
		<%= f.label :title %>
		<br/>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :body %>
		<br/>
		<%= f.text_area :body, :style => "height: 100px;" %>
	</p>

	<h3>Beats</h3>

  	<%= f.fields_for :beats do |beat_form| %>
  		<%= beat_form.file_field :picture %>
  	<% end %>

  	<hr/>
	<p>
		<%= link_to "Back", :back %>
		<%= f.submit %>
	</p>

<%- end %>